Add checkAllFinish in public functions.

diff --git a/deploy/scripts/functions b/deploy/scripts/functions
--- a/deploy/scripts/functions
+++ b/deploy/scripts/functions
@@ -156,6 +156,38 @@ function cpToNodes()
     wait
 }
 
+function checkAllFinish()
+{
+    if [ $# -ne 2 ]
+    then
+        echo "Error! Need two parameters, checkAllFinish <CLUSTER_CONF_IN_HOST> <FILE>"
+        echo "Error command: checkAllFinish $*"
+        return
+    fi
+
+    CLUSTER_CONF=$1
+    FILE=$2
+
+    for ip in `cat ${CLUSTER_CONF} |grep IP_NODE |cut -d "=" -f 2`
+    do
+    {
+        while :
+        do
+            ssh root@${ip} "ls ${LOG_DIR}/done >/dev/null 2>&1"
+
+            if [ $? -eq 0 ]
+            then
+                break
+            fi
+            sleep 10
+        done
+
+    } &
+    done
+    wait
+}
+
+
 function runOnAllNodes()
 {
     if [ $# -ne 2 ]
